### ISSUE TITLE
Delete added Regex pattern from database

### ISSUE THREAD

**Issue by kunnark** [buerokratt/Data-Anonymizer#63]
AS A Data Management Interface user 
I WANT TO delete a given Regex pattern from a database
IN ORDER TO clean my data and keep Regexs list up to date.

Acceptance Criteria:
- [ ]  I can click on 'Delete' on DMI View
- [ ] If I click 'Delete' then confirmation is asked
- [ ] If I confirm then specific Regex pattern is softly deleted from a Postgres database via Ruuter `GET /delete_regex `and ReSQL `POST /delete_regex`

**Comment by turnerrainer** [comment]
@alimuhammadahmer @kunnark

1. This issue is marked as "In progress" but should be groomed first;
2. ACs must contain all REST endpoints used to get the result;
3. _"If I confirm then specific Regex pattern is softly deleted from a Postgres database via Ruuter and ReSQL"_ - please keep in mind that we don't allow using "UPDATE" and "DELETE" SQL queries. This results in writing different kind of SQL queries.

**Comment by alimuhammadahmer** [comment]
Delete Regex Mapping Ruuter Endpoint:
POST /delete_regex
Delete Regex Mapping Resql Endpoint:
POST /delete_regex

**Comment by kunnark** [comment]
> @alimuhammadahmer @kunnark
> 
> 1. This issue is marked as "In progress" but should be groomed first;
> 2. ACs must contain all REST endpoints used to get the result;
> 3. _"If I confirm then specific Regex pattern is softly deleted from a Postgres database via Ruuter and ReSQL"_ - please keep in mind that we don't allow using "UPDATE" and "DELETE" SQL queries. This results in writing different kind of SQL queries.

1. Moved to status 'Backlog'
2. Endpoints added
3. We will add new regex with latest timestamp with the same id to not use nor UPDATE or DELETE
